version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb_movies
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-init:
    image: postgres:17
    depends_on:
      - postgres
    environment:
      PGPASSWORD: postgres
    volumes:
      - ./db-init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db-init/initialize-imdb.sh:/docker-entrypoint-initdb.d/init.sh