version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imdb_movies
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none
      
  postgres-init:
    image: postgres:17
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
      MINIMAL_DATASET: false
    volumes:
      - ../db-init/schema.sql:/schema.sql
      - ../db-init/initialize-imdb.sh:/initialize-imdb.sh
    command: bash -c "sleep 10 && chmod u+x /initialize-imdb.sh && /initialize-imdb.sh"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - default